pool:
  vmImage: 'ubuntu-latest'
variables:
  python.version: 3.6
  project.name: pipelines-python-sample
  feed.name: python-utility
  utility.version: 0.1

stages:
- stage: ConsumePython
  displayName: Consume Python🐍 🏗️
  jobs:
  - job: Consume
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - script: |
        python -m pip install --upgrade pip
        pip install twine keyring artifacts-keyring wheel
      displayName: 'Install dependencies'

    - task: PipAuthenticate@1
      inputs:
        artifactFeeds: $(project.name)/$(feed.name)
        onlyAddExtraIndex: true

    - script: |
        pip install utility==$(utility.version)
        utility xyz

- stage: ConsumePwsh
  displayName: Consume Powershell 🏗️
  jobs:
  - job: BuildPwsh
    steps:
    - task: NuGetAuthenticate@0
    - task: DownloadPackage@1
      inputs:
        packageType: 'nuget'
        feed: $(project.name)/$(feed.name)
        definition: Show-Calendar
        version: '0.0.1'
        downloadPath: .
    - pwsh:  |
        Install-Package Show-Calendar
        # Register-PackageSource -Name "PackageSource" -Location "https://pkgs.dev.azure.com/petjohansson/pipelines-python-sample/_packaging/python-utility/nuget/v2" -ProviderName NuGet
        # Get-PSRepository
