pool:
  vmImage: 'ubuntu-latest'
variables:
  python.version: 3.6
  project.name: pipelines-python-sample
  feed.name: python-utility
  utility.version: 0.1

stages:
- stage: Build
  displayName: Build 🏗️
  jobs:
  - job: Build
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - script: |
        python -m pip install --upgrade pip
        pip install twine keyring artifacts-keyring wheel
      displayName: 'Install dependencies'

    - task: TwineAuthenticate@1
      displayName: Twine Authenticate
      inputs:
        artifactFeed: $(project.name)/$(feed.name)

    - script: |
        pip install --index-url https://pkgs.dev.azure.com/$(project.name)/_packaging/$(feed.name)/pypi/simple utility==$(utility.versiohn)
        utility xyz