trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
variables:
  python.version: 3.6

stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - script: |
        python -m pip install --upgrade pip
        pip install twine keyring artifacts-keyring wheel
      displayName: 'Install dependencies'

    - script: |
        python setup.py bdist_wheel
      displayName: 'Artifact creation'
      workingDirectory: python-module
      

    - task: TwineAuthenticate@1
      displayName: Twine Authenticate
      inputs:
        artifactFeed: pipelines-python-sample/python-utility

    - script: |
       python -m twine upload -r python-utility --config-file $(PYPIRC_PATH) dist/*.whl